spring.application.name=Airline-reservation-System

#Database connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/airticket
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.error.include-message=always
server.error.include-stacktrace=always
