import { ApplicationConfig, provideZoneChangeDetection, importProvidersFrom } from '@angular/core';
import { provideRouter, withComponentInputBinding, withViewTransitions } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { routes } from './app.routes';
import {
  LucideAngularModule,
  Plane,
  Search,
  User,
  MapPin,
  Calendar,
  Clock,
  CreditCard,
  CheckCircle,
  Ticket,
  History,
  LogOut,
  Mail,
  Lock,
  Github,
  Facebook,
  UserPlus,
  Phone,
  Plus,
  PlusCircle,
  Edit2,
  Trash2,
  Shield,
  ShieldCheck,
  ArrowRight,
  Activity,
  DollarSign,
  Users,
  Building2,
  UserCheck,
  ChevronRight,
  FileText,
  Bell,
  Printer,
  Wallet,
  Info,
  Loader2,
  Slash,
  MoreHorizontal,
  X
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes, withComponentInputBinding(), withViewTransitions()),
    provideHttpClient(),
    provideAnimationsAsync(),
    importProvidersFrom(
      LucideAngularModule.pick({
        Plane,
        Search,
        User,
        MapPin,
        Calendar,
        Clock,
        CreditCard,
        CheckCircle,
        Ticket,
        History,
        LogOut,
        Mail,
        Lock,
        Github,
        Facebook,
        UserPlus,
        Phone,
        Plus,
        PlusCircle,
        Edit2,
        Trash2,
        Shield,
        ShieldCheck,
        ArrowRight,
        Activity,
        DollarSign,
        Users,
        Building2,
        UserCheck,
        ChevronRight,
        FileText,
        Bell,
        Printer,
        Wallet,
        Info,
        Loader2,
        Slash,
        MoreHorizontal,
        X
      })
    )
  ]
};
